### ISSUE TITLE
Please add when to enter and exist

### ISSUE THREAD

**Issue by selvanponraj** [julianlk522/stock-scan#1]
Buy when PVS score > ? 
Don't Buy PVS score < ?

Already bought and later PVS score become -ve. this is time to sell the already bought stock.

Any clarification would be helpful

**Comment by julianlk522** [comment]
Prefacing this with: I am no investment professional and nothing here should be considered investment advice.

A neutral (0) Proxy Valuation Score is considered fairly valued. Positive PVS means considered to be trading at a discount. Negative means valued too high.

So if we are going with the old "buy low, sell high" rule, you would be aiming to buy tickers with a currently high PVS and sell low PVSs.

It may be unwise to follow the script's signals so closely. Personally, I like using it to get a broad view of high performers and accumulate a diverse watchlist from them. That helps to see the bigger market picture and identify standout sectors.

Not sure what you mean by "-ve" by the way.

**Comment by selvanponraj** [comment]
Many Thanks for the clarification and I really appreciate for quick reply. My bad I'm saw the reply very late.

1. Do we run scan daily? if yes EOD day and place the order tomorrow opening?
2. I mean -ve was, Bought the ticker based on high PV score and later scan the same ticker is not appearing in the result as it is not matching the input condition in further scans.
3. So I will have to run the PVS for already bought tickers( portfolio) to find out the whats th PVS. if it is Negative then I will sell the stocks. Is my understanding is correct.

Kindly advise.

**Comment by julianlk522** [comment]
When you decide to run the scan and what you do with the output are your decisions to make. But to reiterate, I personally would not use the results as immediate buy/sell signals.

Closing this issue now as the project has no intention of providing explicit trade timing signals as you seem to be requesting.
